import { InternshipRole, Internship } from '../types';

export const INTERNSHIP_ROLES: InternshipRole[] = [
  {
    id: 'web-developer',
    title: 'Web Developer Intern',
    description: 'Build modern web applications using React, Node.js, and other cutting-edge technologies.',
    icon: 'Code',
    color: 'from-blue-500 to-blue-600',
    count: 8,
  },
  {
    id: 'software-developer',
    title: 'Trainee Software Developer',
    description: 'Learn software development fundamentals and contribute to real-world projects.',
    icon: 'Laptop',
    color: 'from-purple-500 to-purple-600',
    count: 12,
  },
  {
    id: 'dotnet-developer',
    title: 'Dotnet Intern',
    description: 'Develop enterprise applications using .NET framework and C# programming.',
    icon: 'Terminal',
    color: 'from-green-500 to-green-600',
    count: 6,
  },
  {
    id: 'business-development',
    title: 'Business Development Intern',
    description: 'Drive growth initiatives and build strategic partnerships for business expansion.',
    icon: 'TrendingUp',
    color: 'from-orange-500 to-orange-600',
    count: 5,
  },
  {
    id: 'human-resources',
    title: 'Human Resource Intern',
    description: 'Support HR operations including recruitment, employee engagement, and policy development.',
    icon: 'Users',
    color: 'from-pink-500 to-pink-600',
    count: 4,
  },
  {
    id: 'digital-marketing',
    title: 'Digital Marketing Intern',
    description: 'Execute digital marketing campaigns across social media, SEO, and paid advertising platforms.',
    icon: 'Megaphone',
    color: 'from-cyan-500 to-cyan-600',
    count: 7,
  },
  {
    id: 'content-creator',
    title: 'Content Creator Intern',
    description: 'Create engaging content for various digital platforms and marketing initiatives.',
    icon: 'Edit',
    color: 'from-indigo-500 to-indigo-600',
    count: 6,
  },
  {
    id: 'software-developer-senior',
    title: 'Software Developer Intern',
    description: 'Work on complex software solutions and contribute to architecture decisions.',
    icon: 'Code2',
    color: 'from-violet-500 to-violet-600',
    count: 10,
  },
  {
    id: 'ui-ux',
    title: 'UI UX Intern',
    description: 'Design intuitive user interfaces and create exceptional user experiences.',
    icon: 'Palette',
    color: 'from-rose-500 to-rose-600',
    count: 8,
  },
  {
    id: 'php-developer',
    title: 'PHP Developer',
    description: 'Build dynamic web applications using PHP, MySQL, and modern frameworks.',
    icon: 'Database',
    color: 'from-amber-500 to-amber-600',
    count: 5,
  },
  {
    id: 'data-analytics',
    title: 'Data Analytics Intern',
    description: 'Analyze data trends and create insights to drive business decisions.',
    icon: 'BarChart3',
    color: 'from-emerald-500 to-emerald-600',
    count: 7,
  },
  {
    id: 'marketing',
    title: 'Marketing Intern',
    description: 'Support marketing campaigns and brand promotion across various channels.',
    icon: 'Target',
    color: 'from-teal-500 to-teal-600',
    count: 6,
  },
  {
    id: 'video-editor',
    title: 'Video Editor Intern',
    description: 'Create compelling video content for marketing and educational purposes.',
    icon: 'Video',
    color: 'from-red-500 to-red-600',
    count: 4,
  },
  {
    id: 'creative',
    title: 'Creative Intern',
    description: 'Contribute to creative projects including branding, design, and multimedia content.',
    icon: 'Sparkles',
    color: 'from-yellow-500 to-yellow-600',
    count: 5,
  },
  {
    id: 'management',
    title: 'Management Intern',
    description: 'Learn management principles and support project coordination and team leadership.',
    icon: 'Crown',
    color: 'from-slate-500 to-slate-600',
    count: 3,
  },
];

// Mock internship data - In a real app, this would come from an API
export const MOCK_INTERNSHIPS: Internship[] = [
  {
    id: '1',
    title: 'Frontend Web Developer Intern',
    company: 'TechStart Solutions',
    location: 'San Francisco, CA',
    locationType: 'Hybrid',
    duration: '3-6 months',
    stipend: '$1,500/month',
    description: 'Join our dynamic team to build responsive web applications using React, TypeScript, and modern CSS frameworks. You\'ll work on real projects that impact thousands of users.',
    requirements: [
      'Currently pursuing Computer Science or related field',
      'Strong knowledge of HTML, CSS, and JavaScript',
      'Experience with React and TypeScript',
      'Understanding of responsive design principles',
      'Familiarity with Git version control'
    ],
    responsibilities: [
      'Develop user interfaces using React and TypeScript',
      'Implement responsive designs from Figma mockups',
      'Collaborate with backend developers on API integration',
      'Participate in code reviews and team meetings',
      'Write clean, maintainable code following best practices'
    ],
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Git', 'REST APIs'],
    roleId: 'web-developer',
    posted: '2024-01-15',
    deadline: '2024-02-15',
    applicationCount: 45,
  },
  {
    id: '2',
    title: 'Full Stack Developer Trainee',
    company: 'Innovation Labs',
    location: 'New York, NY',
    locationType: 'On-site',
    duration: '6 months',
    stipend: '$2,000/month',
    description: 'Comprehensive training program covering full-stack development with mentorship from senior developers. Perfect for beginners looking to start their tech career.',
    requirements: [
      'Basic understanding of web development',
      'Willingness to learn new technologies',
      'Strong problem-solving skills',
      'Good communication skills',
      'Bachelor\'s degree in any field'
    ],
    responsibilities: [
      'Learn modern web development technologies',
      'Build projects under senior developer guidance',
      'Participate in daily standups and sprint planning',
      'Write unit tests for code quality',
      'Document development processes'
    ],
    skills: ['JavaScript', 'Node.js', 'Express', 'MongoDB', 'React'],
    roleId: 'software-developer',
    posted: '2024-01-10',
    deadline: '2024-02-10',
    applicationCount: 67,
  },
  {
    id: '3',
    title: 'Digital Marketing Specialist Intern',
    company: 'Growth Marketing Co.',
    location: 'Austin, TX',
    locationType: 'Remote',
    duration: '4 months',
    stipend: '$1,200/month',
    description: 'Drive digital marketing campaigns across multiple channels including social media, email marketing, and content creation. Learn from experienced marketers in a fast-paced environment.',
    requirements: [
      'Marketing, Business, or Communications major',
      'Strong writing and communication skills',
      'Familiarity with social media platforms',
      'Basic understanding of analytics tools',
      'Creative mindset with attention to detail'
    ],
    responsibilities: [
      'Create content for social media platforms',
      'Assist in email marketing campaigns',
      'Analyze marketing metrics and performance',
      'Support SEO optimization efforts',
      'Participate in marketing strategy meetings'
    ],
    skills: ['Social Media Marketing', 'Content Creation', 'Google Analytics', 'SEO', 'Email Marketing'],
    roleId: 'digital-marketing',
    posted: '2024-01-12',
    deadline: '2024-02-12',
    applicationCount: 34,
  },
];

export const STORAGE_KEYS = {
  TOKEN: 'auth_token',
  USER: 'auth_user',
} as const;